### ISSUE TITLE
How can I use macroexpand and macroexpand-1 in eslisp?

### ISSUE THREAD

**Issue by legokichi** [anko/eslisp#28]
I want to use `macroexpand` and `macroexpand-1` like common lisp.
Or `eslc` compiler need to output s-expression source code after apply macro.

**Comment by anko** [comment]
That is not currently possible.

`macroexpand` would be possible to add, but might break in the future if macros become able to return [estree](https://github.com/estree/estree) objects instead of lists/atoms/strings.

Overall, I am finding it difficult to keep everything feeling familiar to lisp. The macro system still needs lots of work, so I am scared of adding things that would force a certain implementation. I will try to add it in the future.

**Comment by legokichi** [comment]
I see. Thank you for your answer. :+1:
